import { montserrat } from "@/ui/fonts";
import "../globals.css";

import Header from "@/ui/components/Header";

import type { Metadata } from "next";
import { Lang } from "@/lib/definitions";

export const metadata: Metadata = {
  title:
    "Desarrollo Web Full Stack | Aprende Javascript y React | Francis[dev]",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ lang: "es" }, { lang: "en" }];
}

export default function RootLayout({
  params,
  children,
}: {
  params: { lang: Lang };
  children: React.ReactNode;
}) {
  return (
    <html lang={params.lang} className="dark">
      <body className={`${montserrat.className}`}>
        <Header lang={params.lang} />
        {children}
      </body>
    </html>
  );
}
