import type { Metadata } from "next";
import { montserrat } from "@/ui/fonts";
import "./globals.css";
import Header from "@/ui/components/Header";

export const metadata: Metadata = {
  title:
    "Desarrollo Web Full Stack | Aprende Javascript y React | Francis[dev]",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
